src/steps/ValidationStep/ValidationStep.tsx, src/theme.ts
-fixed validation step heading theming
-fixed switch label alignment
=> bug UGN-282 - fixed switch label alignment

src/components/Selects/MenuPortal.tsx, src/steps/MatchColumnsStep/tests/MatchColumnsStep.test.tsx
=> Fix UGN-281 Make dropdown above scrollbar

src/steps/ValidationStep/ValidationStep.tsx, src/steps/ValidationStep/tests/ValidationStep.test.tsx
- Fix bug where Table would lose data if changes were made with filter on
=> Fix UGN-284 table losing data on filter

src/components/Providers.tsx, src/theme.ts
- remove enforced button color in dropzone
- fixes #88
=> Fix UGN-337 remove enforced button color in dropzone

src/ReactSpreadsheetImport.tsx, src/components/ContinueButton.tsx, src/steps/MatchColumnsStep/MatchColumnsStep.tsx, src/steps/MatchColumnsStep/components/ColumnGrid.tsx, src/steps/MatchColumnsStep/components/UserTableColumn.tsx, src/steps/MatchColumnsStep/utils/normalizeTableData.ts, src/steps/SelectHeaderStep/SelectHeaderStep.tsx, src/steps/SelectHeaderStep/components/SelectHeaderTable.tsx, src/steps/SelectHeaderStep/components/columns.tsx, src/steps/SelectSheetStep/SelectSheetStep.tsx, src/steps/SelectSheetStep/stories/SelectSheet.stories.tsx, src/steps/UploadFlow.tsx, src/steps/UploadStep/UploadStep.tsx, src/steps/UploadStep/components/DropZone.tsx, src/steps/UploadStep/stories/Upload.stories.tsx, src/steps/ValidationStep/ValidationStep.tsx, src/steps/ValidationStep/tests/ValidationStep.test.tsx, src/stories/mockRsiValues.ts, src/types.ts
- added hook to each step
- all step hooks are async - allows network calls
- added loading states to indicate async actions
example:
=> feat UGN-328 UGN-331 - add hooks to each step

package-lock.json, package.json, src/components/FadingWrapper.tsx, src/steps/SelectHeaderStep/SelectHeaderStep.tsx, src/steps/UploadStep/UploadStep.tsx, src/steps/UploadStep/components/FadingOverlay.tsx, src/steps/ValidationStep/ValidationStep.tsx, src/steps/ValidationStep/utils/dataMutations.ts, src/stories/mockRsiValues.ts, src/tests/setup.ts, src/theme.ts
Cleaned up fixes by @jtordgeman
- use `uuid` library instead of crypto for older Node versions when serverside rendering
- fix how tables look in firefox
- fix "fade" effect for safari/firefox
=> Fixes for different environments

src/steps/Steps.tsx, src/steps/ValidationStep/ValidationStep.tsx
- hide stepper
- fix validation step header
=> Fix UGN-314 make RSI usable on mobile

README.md, src/index.ts, src/steps/MatchColumnsStep/tests/MatchColumnsStep.test.tsx, src/steps/SelectHeaderStep/tests/SelectHeaderStep.test.tsx, src/steps/UploadFlow.tsx
=> chore UGN-354 - update readme to include initialStepState

src/ReactSpreadsheetImport.tsx, src/steps/UploadStep/components/DropZone.tsx, src/types.ts
If true, plain text parsing will not parse values.
=> add parseRaw parameter

src/steps/SelectHeaderStep/tests/SelectHeaderStep.test.tsx
=> UGN-360 - parseRaw:true parameter tests

README.md, src/ReactSpreadsheetImport.tsx, src/types.ts
=> chore UGN-361 - update docs and set parseRaw: true as default

package.json, src/ReactSpreadsheetImport.tsx, src/components/ModalCloseButton.tsx, src/components/ModalWrapper.tsx, src/components/Selects/MenuPortal.tsx, src/components/Table.tsx, src/steps/ValidationStep/components/columns.tsx, src/theme.ts, src/types.ts
- Added RTL support via chakra and data-grid rtl props 
- custom changes made to react-chakra-select menu, ModalCloseButton, ValidationStep columns
- updated package.json clean script
=> feat UGN-362 - adds RTL support

.github/config/configuration.json, .github/workflows/release.yaml
- bumped mikepenz/release-changelog-builder-action@v3 version in release.yaml
- erased unnecessary configurations
=> fixes release notes categories and populates PR numbers correctly.

src/steps/UploadStep/components/DropZone.tsx, src/steps/ValidationStep/ValidationStep.tsx, src/stories/Default.stories.tsx
- Enabling "dense" flag for parsing.
- Refactoring onSubmit to reduce calculations
- Displaying only first 100 rows in storybook after submit.
=> feat UGN-369 - Improve performance for large files

src/steps/UploadFlow.tsx, src/steps/UploadStep/UploadStep.tsx, src/steps/UploadStep/components/DropZone.tsx, src/steps/ValidationStep/ValidationStep.tsx, src/steps/ValidationStep/stories/Validation.stories.tsx, src/steps/ValidationStep/tests/ValidationStep.test.tsx, src/types.ts
- Pass uploaded file to onSubmit
=> feat UGN-368 - original file in onSubmit

src/hooks/useRsiInitialStep.ts, src/steps/Steps.tsx
Hi,
It should fix this [#171](https://github.com/UgnisSoftware/react-spreadsheet-import/issues/171) :)
=> Fixes stepper unsynchronized with step's content

src/steps/UploadStep/components/DropZone.tsx
=> bugfix UGN-370 - fixes error on non-permitted file extensions

.storybook/main.ts
Update storybook `staticDir` to include static files in the final build.
=> UGN-371 bugfix - fix example csv download

src/steps/UploadStep/components/DropZone.tsx
Add codepage: 65001 to encoding issue on  import csv files
=> Fix csv encoding problem

.github/workflows/test.yaml, .gitignore, e2e/example.spec.ts, package-lock.json, package.json, playwright.config.ts, src/steps/SelectHeaderStep/SelectHeaderStep.tsx, src/steps/ValidationStep/ValidationStep.tsx, src/stories/Default.stories.tsx, src/stories/mockRsiValues.ts, src/theme.ts
Add browser tests to catch errors with different browsers. And add visual regression tests to avoid unintentional style changes.
=> Add browser testing

package-lock.json, package.json
Updates storybook for https://github.com/UgnisSoftware/react-spreadsheet-import/security/dependabot/31 and babel for https://github.com/UgnisSoftware/react-spreadsheet-import/security/dependabot/32.
=> Update vulnerable packages

src/theme.ts
Fixes https://github.com/UgnisSoftware/react-spreadsheet-import/issues/142
=> Fix mobile viewport size calculation

src/steps/MatchColumnsStep/components/MatchIcon.tsx, src/steps/Steps.tsx, src/steps/UploadStep/components/columns.tsx, src/steps/ValidationStep/components/columns.tsx
Fixes Safari error where SVG thows error when getting rem values.
Resolves #204.
=> Fix SVG not accepting rem values

.eslintrc, src/ReactSpreadsheetImport.tsx
Addressing #262 - moved default props inside component.
=> Remove defaultProps usage

src/utils/steps.ts
Addressing the issues raised in this issue
https://github.com/UgnisSoftware/react-spreadsheet-import/issues/250 
Using recomended fix from @agnar-nomad
=> Bug fix: Incorrect step indicator if initialStepState is provided
